// Code generated by Slice Machine. DO NOT EDIT.

import AboutUs from './AboutUs/index.svelte';
import BentoBox from './BentoBox/index.svelte';
import Documentation from './Documentation/index.svelte';
import FeatureExtraction from './FeatureExtraction/index.svelte';
import Hero from './Hero/index.svelte';
import Results from './Results/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	about_us: AboutUs,
	bento_box: BentoBox,
	documentation: Documentation,
	feature_extraction: FeatureExtraction,
	hero: Hero,
	results: Results,
	rich_text: RichText
};
